//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EYWebServices.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addition", ReplyAction="*")]
        int addition(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addition", ReplyAction="*")]
        System.Threading.Tasks.Task<int> additionAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/subtraction", ReplyAction="*")]
        int subtraction(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/subtraction", ReplyAction="*")]
        System.Threading.Tasks.Task<int> subtractionAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multiplication", ReplyAction="*")]
        int multiplication(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multiplication", ReplyAction="*")]
        System.Threading.Tasks.Task<int> multiplicationAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/division", ReplyAction="*")]
        int division(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/division", ReplyAction="*")]
        System.Threading.Tasks.Task<int> divisionAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : EYWebServices.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<EYWebServices.ServiceReference1.WebService1Soap>, EYWebServices.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int addition(int a, int b) {
            return base.Channel.addition(a, b);
        }
        
        public System.Threading.Tasks.Task<int> additionAsync(int a, int b) {
            return base.Channel.additionAsync(a, b);
        }
        
        public int subtraction(int a, int b) {
            return base.Channel.subtraction(a, b);
        }
        
        public System.Threading.Tasks.Task<int> subtractionAsync(int a, int b) {
            return base.Channel.subtractionAsync(a, b);
        }
        
        public int multiplication(int a, int b) {
            return base.Channel.multiplication(a, b);
        }
        
        public System.Threading.Tasks.Task<int> multiplicationAsync(int a, int b) {
            return base.Channel.multiplicationAsync(a, b);
        }
        
        public int division(int a, int b) {
            return base.Channel.division(a, b);
        }
        
        public System.Threading.Tasks.Task<int> divisionAsync(int a, int b) {
            return base.Channel.divisionAsync(a, b);
        }
    }
}
