// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetcorewebapi_migrationDemo.model;

namespace aspnetcorewebapi_migrationDemo.Migrations
{
    [DbContext(typeof(empDBContext))]
    [Migration("20230330115153_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("aspnetcorewebapi_migrationDemo.model.employee", b =>
                {
                    b.Property<int>("empid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("empfirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emplastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("empid");

                    b.ToTable("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
