//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerss
    {
        public int customer_id { get; set; }
        public string cust_name { get; set; }
        public string city { get; set; }
        public Nullable<int> grade { get; set; }
        public Nullable<int> salesman_id { get; set; }
    }
}
